### ISSUE TITLE
Update firebase_storage dependency to ^7.0.0

### ISSUE THREAD

**Issue by thearaks** [mattreid1/firebase_image#23]
They've just release a new version of the FlutterFire libraries, firebase_storage has reached version 6.0.0.
There should be no significant changes since 5.0.0, just updating the pubspec.yaml should be enough.

It would be nice to have the dependency updated soon since the current one prevents from upgrading all the other FlutterFire dependencies in the app!
Thank you!

**Comment by sebasbose** [comment]
I am having the same issue, due to stability reasons I am updating my project pubspec.yaml dependencies' versions to the latests; therefore, I can't use Firebase_Image anymore. Please update ASAP! By the way, thanks for you awesome work!

**Comment by ycv005** [comment]
@mattreid1 have a look at it.

**Comment by mattreid1** [comment]
Apologies for the delay - been really busy at work. Will try to have a look by Friday. Thanks for the support!

**Comment by thearaks** [comment]
For anyone who need to update the FlutterFire dependencies: you can use my forked development branch temporarily while we wait for a new official release.

Just declare the `firebase_image` dependency as follows in your `pubspec.yaml`:

```yaml
  firebase_image:
    git:
      url: git://github.com/thearaks/firebase_image.git
      ref: feature/firebase_storage_6
```

**Comment by lukepighetti** [comment]
Friendly ping.

**Comment by lukepighetti** [comment]
I believe this was closed by https://github.com/mattreid1/firebase_image/commit/3e190cb495fbe7f13c6c2845085411ea7f77b731

**Comment by thearaks** [comment]
See #30 for Flutter 2.0 and Dart 2.12 compatibility and dependency set to firebase_storage ^8.0.0.

As usual, until the PR gets merged and the plugin updated, you can use my fork branch:
```yaml
  firebase_image:
    git:
      url: git://github.com/thearaks/firebase_image.git
      ref: feature/firebase_storage_8
```
